[package]
name = "MOES-Chip8"
version = "0.1.0"
authors = ["David Gibb <dgibb802@gmail.com>"]

[dependencies]
libc = "0.2.2"
nickel = "*"
hyper = "*"
byteorder = "*"
serde = "*"
serde_json = "*"
ws = "*"
